import os
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_core.documents import Document
from chromadb.utils.embedding_functions import DefaultEmbeddingFunction


class OnnxEmbeddings:
    def __init__(self):
        self._fn = DefaultEmbeddingFunction()
    def embed_documents(self, texts):
        return [list(v) for v in self._fn(texts)]
    def embed_query(self, text):
        return list(self._fn([text])[0])

DOCUMENTS = [
    {"id": 1, "title": "What is Gymnastics?", "language": "en", "category": "Foundations", "content": ("WHAT IS GYMNASTICS?\n\nGymnastics is a sport that combines strength, flexibility, balance, coordination, and movement technique across a range of disciplines and apparatus.\n\nIts origins trace back to ancient Greece, where gymnastic exercises were part of physical and military education. The modern sport took shape in 19th-century Europe, largely through the work of Friedrich Ludwig Jahn in Germany, widely regarded as the father of gymnastics. Gymnastics was included in the first modern Olympic Games in Athens in 1896 and has been part of every Summer Olympics since.\n\nThe sport is governed internationally by the Federation Internationale de Gymnastique (FIG), founded in 1881 and headquartered in Lausanne, Switzerland. FIG establishes the competition rules through the Code of Points, organizes the World Championships, and oversees the Olympic gymnastics program. The organization has member federations in over 140 countries.\n\nAthletes typically begin training in early childhood and progress through national competition systems toward international competition. The highest level of competition is the Olympic Games.")},
    {"id": 2, "title": "Types of Gymnastics", "language": "en", "category": "Foundations", "content": ("TYPES OF GYMNASTICS\n\nGymnastics comprises six disciplines, each with its own rules, apparatus, and physical requirements.\n\nWOMEN'S ARTISTIC GYMNASTICS (WAG): Female gymnasts compete on four apparatus: vault, uneven bars, balance beam, and floor exercise.\n\nMEN'S ARTISTIC GYMNASTICS (MAG): Male gymnasts compete on six apparatus: floor exercise, pommel horse, still rings, vault, parallel bars, and horizontal bar.\n\nRHYTHMIC GYMNASTICS: Performed to music using hand apparatus (rope, hoop, ball, clubs, or ribbon), with an emphasis on flexibility, coordination, and apparatus technique rather than acrobatic tumbling.\n\nTRAMPOLINE GYMNASTICS: Athletes perform acrobatic skills on a trampoline, reaching heights of up to 8 meters. Routines are evaluated on difficulty, execution, and time of flight.\n\nAEROBIC GYMNASTICS: Consists of continuous routines performed to music, demonstrating strength, coordination, and cardiorespiratory endurance. It is competed individually, in pairs, trios, or groups.\n\nACROBATIC GYMNASTICS: Involves groups of 2 to 4 gymnasts performing dynamic and balance elements together, including throws, catches, and partner balances.")},
    {"id": 3, "title": "Women's Artistic Gymnastics: The 4 Apparatus", "language": "en", "category": "Foundations", "content": ("WOMEN'S ARTISTIC GYMNASTICS: THE 4 APPARATUS\n\nVAULT: The gymnast sprints approximately 25 meters down the runway, takes off from a springboard, pushes off the vaulting table, and executes a skill in the air before landing. The flight phase lasts approximately 1 to 2 seconds. Scores are based on the difficulty of the vault and the quality of execution and landing.\n\nUNEVEN BARS: Two horizontal bars are set at different heights, with the high bar at approximately 2.50 m and the low bar at 1.70 m. The gymnast performs a continuous routine of swings, releases, and catches between the two bars. Evaluation focuses on swing technique, release skills, and body position.\n\nBALANCE BEAM: The beam is 5 meters long and 10 centimeters wide, raised 125 centimeters above the floor. Gymnasts perform a routine of 70 to 90 seconds combining jumps, turns, acrobatic elements, and choreography. Any step, fall, or loss of balance results in a deduction.\n\nFLOOR EXERCISE: The routine is performed on a 12 by 12 meter sprung floor to music, lasting 70 to 90 seconds. It includes tumbling passes, jumps, turns, and choreographic sequences. Going outside the boundary lines results in a deduction.")},
    {"id": 4, "title": "Men's Artistic Gymnastics: The 6 Apparatus", "language": "en", "category": "Foundations", "content": ("MEN'S ARTISTIC GYMNASTICS: THE 6 APPARATUS\n\nFLOOR: Tumbling passes and strength elements are performed on a 12 by 12 meter sprung floor, without musical accompaniment at the international level.\n\nPOMMEL HORSE: The gymnast performs continuous circular and scissor movements on a leather horse with two handles, supporting the body on the arms throughout. Any stop in movement or contact with the leg results in a deduction.\n\nSTILL RINGS: Two rings are suspended from cables at 2.75 meters. The gymnast performs swing elements and static strength holds, such as the iron cross or planche, while minimizing movement in the rings themselves.\n\nVAULT: Performed on the same apparatus as in the women's discipline, at higher difficulty levels.\n\nPARALLEL BARS: Two bars are set at equal height (195 cm), approximately 42 cm apart. Gymnasts perform swinging, release, and strength elements both between and above the bars.\n\nHORIZONTAL BAR: A single bar is set at 280 cm. Gymnasts perform giant swings and release skills, briefly releasing the bar entirely, before catching it again and finishing with a dismount.")},
    {"id": 5, "title": "Rhythmic Gymnastics", "language": "en", "category": "Foundations", "content": ("RHYTHMIC GYMNASTICS\n\nRhythmic gymnastics combines movement drawn from dance and ballet with the technical manipulation of hand apparatus. Competitions are held in individual and group formats.\n\nGymnasts compete with five types of hand apparatus:\n\nROPE: Jumping, throwing, and rotating the rope.\n\nHOOP: Rolling along the body, throwing, rotating, and passing through.\n\nBALL: Rolling on the body, bouncing, and throwing.\n\nCLUBS: Throwing and catching skills performed with two clubs simultaneously.\n\nRIBBON: Continuous movement that draws shapes in the air; contact with the floor results in a deduction.\n\nIn the group event, five gymnasts perform together, either with identical apparatus or a combination of two different types.\n\nThe discipline does not include acrobatic tumbling. Evaluation focuses on flexibility, body movement technique, and the quality of apparatus handling. Russia, Bulgaria, Israel, and Spain have historically achieved the strongest international results.")},
    {"id": 6, "title": "Trampoline, Aerobic, and Acrobatic Gymnastics", "language": "en", "category": "Foundations", "content": ("TRAMPOLINE, AEROBIC, AND ACROBATIC GYMNASTICS\n\nTRAMPOLINE GYMNASTICS: Athletes perform a routine of 10 consecutive acrobatic skills on a trampoline, reaching heights of up to 8 to 10 meters. Each skill must be different. Routines are evaluated on the difficulty of the skills performed, the quality of execution, and the total time of flight, which measures how long the athlete stays in the air across the entire routine. Trampoline also includes two related disciplines: double mini trampoline (a smaller apparatus with a run-up) and tumbling (acrobatic skills performed on a sprung runway without a trampoline).\n\nAEROBIC GYMNASTICS: Routines last 60 to 90 seconds and consist of continuous, high-intensity movement performed to music. Athletes demonstrate strength, flexibility, coordination, and cardiorespiratory endurance through a combination of aerobic steps and gymnastics skills. Competition categories include individual men, individual women, mixed pairs, trios, and groups of six.\n\nACROBATIC GYMNASTICS: Athletes compete in partnerships: women's pairs, men's pairs, mixed pairs, women's groups (3 athletes), and men's groups (4 athletes). Routines include two types of elements: balance elements, where partners hold static positions together, and dynamic elements, where one partner throws, catches, or releases another. Routines are performed to music and evaluated on difficulty, execution, and artistry.")},
    {"id": 7, "title": "Types of Gymnastics Competitions", "language": "en", "category": "Competitions", "content": ("TYPES OF GYMNASTICS COMPETITIONS\n\nGymnastics competitions are organized at several levels, from local club events to the Olympic Games.\n\nOLYMPIC GAMES: Held every four years, the Olympics represent the highest level of gymnastics competition. Countries qualify teams and individual gymnasts based on results at the preceding World Championships and qualification events.\n\nWORLD CHAMPIONSHIPS: Organized annually by FIG, the World Championships are the most important competition outside of the Olympic cycle. Athletes compete in team, individual all-around, and individual apparatus events.\n\nWORLD CUP SERIES: A series of individual apparatus competitions held in different countries throughout the year. Athletes accumulate points toward an overall World Cup ranking.\n\nCONTINENTAL CHAMPIONSHIPS: Each continent organizes its own championship. In Europe, the European Gymnastics Championships are held every two years and are open to all European FIG member federations.\n\nAt the national level, each country organizes its own competition system. In Slovenia, the Gymnastics Federation of Slovenia (GZS) oversees national championships, regional competitions, and age-group events for gymnasts at all levels, from beginners to the national team.")},
    {"id": 8, "title": "How a WAG Competition Works", "language": "en", "category": "Competitions", "content": ("HOW A WAG COMPETITION WORKS\n\nA Women's Artistic Gymnastics competition typically follows a structured format across multiple rounds.\n\nPODIUM TRAINING: Before the competition begins, teams have a period of familiarization on the competition apparatus, known as podium training. This allows gymnasts to adjust to the specific equipment and environment.\n\nQUALIFICATIONS: All teams and individual gymnasts compete in the qualification round. Each gymnast performs on some or all of the four apparatus. The results from qualifications determine who advances to the finals and serve as the team competition scores.\n\nTEAM FINAL: The top 8 teams from qualifications advance. Each country fields up to 5 gymnasts, with 4 competing on each apparatus and the top 3 scores counting toward the team total.\n\nINDIVIDUAL ALL-AROUND FINAL: The top 24 gymnasts from qualifications, with a maximum of 2 per country, compete on all four apparatus. The combined score across all four determines the all-around champion.\n\nEVENT FINALS: The top 8 gymnasts on each individual apparatus from qualifications, with a maximum of 2 per country, compete again. Each apparatus has its own champion.\n\nDuring the competition, gymnasts rotate between apparatus in a fixed order: vault, uneven bars, balance beam, and floor exercise. Each team or gymnast performs in a designated subdivision based on qualification scores.")},
    {"id": 9, "title": "What Does It Take to Be a Gymnast?", "language": "en", "category": "The Athlete", "content": ("WHAT DOES IT TAKE TO BE A GYMNAST?\n\nGymnastics is a sport that requires a combination of physical and mental qualities developed over many years of training.\n\nTRAINING VOLUME: Elite gymnasts typically train 7 to 8 hours per day, which amounts to roughly 40 to 50 hours per week. At younger and lower levels, training is less intensive, but consistent practice over years is necessary to develop the required skills.\n\nSTARTING AGE: Most competitive gymnasts begin training between the ages of 3 and 6. At the elite international level, gymnasts typically reach their peak competitive years between the ages of 15 and 24 in the women's artistic discipline.\n\nPHYSICAL QUALITIES: The sport requires flexibility, strength relative to body weight, coordination, spatial awareness, and the ability to learn and repeat complex movement patterns precisely.\n\nMENTAL DEMANDS: Gymnasts must manage performance under pressure, overcome fear when learning new skills, and maintain consistency across multiple events in a single competition. Mental preparation is considered as important as physical training at the elite level.\n\nEDUCATION: Due to the high number of training hours, elite gymnasts are frequently homeschooled or follow adapted educational programs. This allows them to maintain their training schedule while fulfilling their academic requirements.")},
    {"id": 10, "title": "Notable Gymnasts in History", "language": "en", "category": "The Athlete", "content": ("NOTABLE GYMNASTS IN HISTORY\n\nSeveral gymnasts have shaped the history of Women's Artistic Gymnastics through their performances and contributions to the sport.\n\nLARISA LATYNINA (USSR): Competed between 1956 and 1964, winning 18 Olympic medals: 9 gold, 5 silver, and 4 bronze. This remained the record for most Olympic medals by any athlete for nearly 50 years.\n\nVERA CASLAVSKA (CZECHOSLOVAKIA): Won 7 Olympic gold medals across the 1964 and 1968 Games and is regarded as one of the defining figures in the sport's early development.\n\nOLGA KORBUT (USSR): Gained international attention at the 1972 Munich Olympics, introducing skills of a difficulty not previously seen in competition and bringing a new public audience to the sport.\n\nNADIA COMANECI (ROMANIA): Became the first gymnast in Olympic history to receive a perfect score of 10.0, at the 1976 Montreal Games at the age of 14. She received seven perfect scores during those Games.\n\nSIMONE BILES (USA): Has accumulated more World Championship medals than any other gymnast in history. She has introduced multiple skills of unprecedented difficulty, several of which now carry her name in the Code of Points. She competed at the 2016 and 2020 Olympic Games, winning multiple gold medals at each.")},
    {"id": 11, "title": "How WAG Scoring Works", "language": "en", "category": "Judging System", "content": ("HOW WAG SCORING WORKS\n\nTHE OPEN-ENDED SCORING SYSTEM\n\nWomen's Artistic Gymnastics uses an open-ended scoring system introduced after the 2004 Olympic Games. Under this system, scores are not capped at 10.0. Instead, the final score is the sum of two separate components:\n\nFinal Score = Difficulty Score (D) + Execution Score (E) - Neutral Deductions\n\nThe Difficulty Score reflects what the gymnast attempts, and the Execution Score reflects how well she performs it. Neutral Deductions are applied for specific rule violations and are subtracted from the total.\n\nTHE TWO MAIN COMPONENTS\n\nThe Difficulty Score (D) has no maximum limit. A gymnast who includes more difficult skills and fulfills more composition requirements will receive a higher D score.\n\nThe Execution Score (E) starts at a maximum of 10.0. Judges deduct for technical and artistic errors throughout the routine. The final E score reflects how cleanly and precisely the gymnast performed.\n\nTIEBREAKER RULE\n\nIf two gymnasts finish with the same final score, the gymnast with the higher Difficulty Score is ranked higher. This rule reflects the principle that greater technical difficulty is rewarded when execution is equal.")},
    {"id": 12, "title": "The Difficulty Score (D Score)", "language": "en", "category": "Judging System", "content": ("THE DIFFICULTY SCORE (D SCORE)\n\nThe Difficulty Score is calculated by the two D-panel judges and consists of three parts: the value of the gymnast's skills, the Composition Requirements, and any Connection Value bonuses.\n\nELEMENT VALUES\n\nEvery skill in the FIG Code of Points is assigned a difficulty letter from A to I:\nA = 0.1, B = 0.2, C = 0.3, D = 0.4, E = 0.5, F = 0.6, G = 0.7, H = 0.8, I = 0.9\n\nOn floor, beam, and uneven bars, only the 8 highest-valued elements are counted toward the D score. On vault, the routine consists of a single skill whose value is listed directly in the FIG Code of Points.\n\nCOMPOSITION REQUIREMENTS (CR)\n\nEach apparatus has specific Composition Requirements. Each fulfilled requirement adds 0.5 points to the D score, with a maximum of 2.0 points available from this component. If a gymnast does not include a required element type, she simply does not earn those points. There is no separate penalty for the omission.\n\nCONNECTION VALUE (CV)\n\nGymnasts can earn bonus tenths (0.10 or 0.20) by directly connecting certain elements. These bonuses vary by apparatus and are specified in the FIG Code of Points.")},
    {"id": 13, "title": "The Execution Score (E Score)", "language": "en", "category": "Judging System", "content": ("THE EXECUTION SCORE (E SCORE)\n\nThe Execution Score begins at 10.0 for every routine. A panel of five judges evaluates the gymnast's technical precision, body form, and artistry. Each error results in a deduction from that starting value.\n\nTo reduce the effect of individual bias, the highest and lowest scores from the five judges are removed. The final E score is the average of the remaining three.\n\nTHE DEDUCTION SCALE\n\nThe FIG Code of Points uses four standard deduction values:\nSmall error: 0.10\nMedium error: 0.30\nLarge error: 0.50\nFall: 1.00\n\nA fall is defined as an uncontrolled loss of contact with the apparatus or floor and always results in a 1.00 deduction.\n\nMAXIMUM DEDUCTION PER ELEMENT\n\nFor any single skill, the maximum execution deduction is 0.80, regardless of how many errors are observed in that element. A fall is treated separately and is always penalized as a 1.00 deduction; it is not subject to this cap.\n\nEXAMPLES OF EXECUTION ERRORS\n\nBent knees: 0.10 or 0.30 depending on severity.\nSeparated legs when they should be together: 0.10 or 0.30.\nFlexed feet: 0.10 or 0.30.\nInsufficient height or amplitude of a skill: 0.10 or 0.30.\nSteps on landing: 0.10 (small step) or 0.30 (large step or stagger).\nLoss of balance on beam: 0.10, 0.30, or 0.50 depending on severity.")},
    {"id": 14, "title": "The Judging Panel", "language": "en", "category": "Judging System", "content": ("THE JUDGING PANEL\n\nAt FIG-sanctioned competitions, each apparatus is evaluated by a panel of judges divided into two groups with distinct responsibilities.\n\nD PANEL (DIFFICULTY)\n\nThe D panel consists of two judges (D1 and D2). They identify every skill performed, verify that Composition Requirements are met, and calculate the total Difficulty Score. Both judges work independently and then compare results. If their scores differ beyond the permitted range, the matter is referred to a Superior Jury.\n\nE PANEL (EXECUTION)\n\nThe E panel consists of five judges (E1 through E5). Each assesses the routine independently. After the routine, the highest and lowest scores are removed and the average of the remaining three produces the final E score.\n\nREFEREE\n\nThe referee oversees the entire process: gives the starting signal, monitors neutral deductions such as time violations, and ensures the competition follows FIG regulations.\n\nINQUIRIES\n\nAfter a score is announced, the gymnast's coach may submit a formal inquiry to challenge the D score only. E score decisions are final and cannot be challenged. Inquiries must be submitted within the designated time window and require a fee, which is refunded if the inquiry succeeds.")},
    {"id": 15, "title": "Deductions on Vault and Uneven Bars", "language": "en", "category": "Judging System", "content": ("DEDUCTIONS ON VAULT AND UNEVEN BARS\n\nVAULT\n\nOn vault, each gymnast performs a single skill. Every vault in the FIG Code of Points has a predetermined difficulty value, so the D score is simply the value of the vault performed. The E score starts at 10.0 and is assessed by the five E-panel judges.\n\nCommon deductions on vault:\nLanding steps: 0.10 (small step) or 0.30 (large step or stagger).\nFall on landing: 1.00.\nFlexed feet during flight: 0.10 or 0.30.\nBent knees: 0.10 or 0.30.\nLow or under-rotated vault: 0.30 or 0.50.\nTouching the mat with hands on landing: 0.50.\n\nIn vault finals at major competitions, gymnasts perform two vaults and the two scores are averaged.\n\nUNEVEN BARS\n\nA bars routine includes up to 8 counted elements. The gymnast must meet the Composition Requirements of the apparatus.\n\nCommon deductions on bars:\nBent knees or piked position when a straight body is required: 0.10 or 0.30.\nFlexed feet: 0.10 or 0.30.\nInsufficient height on release elements: 0.10 or 0.30.\nSteps or hop on dismount landing: 0.10 or 0.30.\nFall from the bar: 1.00.\n\nFALL RECOVERY ON BARS: When a gymnast falls from the bar, a deduction of 1.00 is immediately applied to her E score. She then has 30 seconds to remount and continue. If she does not remount within 30 seconds, the routine is considered terminated and she receives no credit for any elements she did not perform.")},
    {"id": 16, "title": "Deductions on Balance Beam and Floor Exercise", "language": "en", "category": "Judging System", "content": ("DEDUCTIONS ON BALANCE BEAM AND FLOOR EXERCISE\n\nBALANCE BEAM\n\nA beam routine must last between 70 and 90 seconds. If the routine exceeds 90 seconds, a neutral deduction of 0.10 is applied for each full second over the limit.\n\nCommon deductions on beam:\nSmall loss of balance, visible but controlled: 0.10.\nMore significant loss of balance, with a bent or hunched body: 0.30.\nLoss of balance severe enough to touch the beam with hands: 0.50.\nFall from the beam: 1.00.\nBent knees: 0.10 or 0.30.\nLanding step after a skill: 0.10 (small) or 0.30 (large).\n\nFALL RECOVERY ON BEAM: When a gymnast falls from the beam, a deduction of 1.00 is immediately applied to her E score. She then has 10 seconds to remount and continue. If she does not remount within 10 seconds, the routine is terminated and she receives no credit for any elements she did not perform.\n\nFLOOR EXERCISE\n\nA floor routine must last between 70 and 90 seconds and is performed to music. If the routine exceeds 90 seconds, a neutral deduction of 0.10 per second over the limit is applied.\n\nCommon deductions on floor:\nLanding steps: 0.10 (small step) or 0.30 (large step or stagger).\nBent knees or legs apart on a salto: 0.10 or 0.30.\nFlexed feet: 0.10 or 0.30.\nOut of bounds: 0.30 per foot that lands completely outside the boundary.\n\nThe floor area is 12 by 12 meters. A foot landing fully outside the line is penalized; a foot on the line is not.")},
    {"id": 17, "title": "Gimnastika v Sloveniji", "language": "sl", "category": "Slovenija", "content": ("GIMNASTIKA V SLOVENIJI\n\nGIMNASTIČNA ZVEZA SLOVENIJE\n\nGimnastična zveza Slovenije (GZS) je nacionalna krovska organizacija za gimnastiko v Sloveniji. Je članica Mednarodne gimnastične zveze (FIG) in Evropske gimnastične zveze (UEG). GZS organizira tekmovanja na vseh ravneh, od začetniških kategorij do državnega in mednarodnega nivoja, ter skrbi za razvoj gimnastike v državi.\n\nSLOVENIJA NA MEDNARODNEM PRIZORIŠČU\n\nPo osamosvojitvi leta 1991 je Slovenija začela nastopati na mednarodnih tekmovanjih pod lastno zastavo. Slovenske gimnastičarke so se uvrstile na Olimpijske igre, Svetovna in Evropska prvenstva ter različna mednarodna tekmovanja serije World Cup. Kljub temu da je Slovenija majhna država z omejenim številom tekmovalk, je s posamičnimi nastopi dosegla odmevne rezultate na najvišji ravni.\n\nRAZVOJ ŠPORTA\n\nGimnastika v Sloveniji se začne že v zgodnjem otroštvu. Mladi gimnastičarji se razvijajo v klubih po vsej državi, ki delujejo v okviru GZS. Naprednejše tekmovalke, ki dosežejo ustrezen nivo, se vključijo v program državne reprezentance in tekmujejo po pravilih FIG.")},
    {"id": 18, "title": "Slovenske gimnastičarke", "language": "sl", "category": "Slovenija", "content": ("SLOVENSKE GIMNASTIČARKE\n\nTEJA BELAK\n\nTeja Belak je ena najpomembnejših slovenskih gimnastičark. Nastopila je na Olimpijskih igrah v Riu de Janeiru leta 2016 in v Tokiu leta 2020, s čimer je postala ena redkih slovenskih gimnastičark z dvema olimpijskima nastopoma. Je večkratna državna prvakinja in je Slovenijo zastopala na Evropskih in Svetovnih prvenstvih.\n\nTJAŠA KYSSELEF\n\nTjaša Kysselef je ena najdlje delujočih slovenskih tekmovalk na mednarodni ravni. Nastopala je na številnih Evropskih prvenstvih, Svetovnih prvenstvih in tekmovanjih serije World Cup.\n\nLUCIJA HRIBAR\n\nLucija Hribar je trenutno najbolj uspešna gimnastičarka. Leta 2024 se je na olimpijskih igrah v Parizu uvrstila v finale mnogoboja, kar je za Slovenijo najboljši dosežek doslej.")},
    {"id": 19, "title": "Tekmovalni sistem GZS", "language": "sl", "category": "Slovenija", "content": ("TEKMOVALNI SISTEM GZS\n\nNIVOJI TEKMOVANJ V SLOVENIJI\n\nV Sloveniji so tekmovanja v ženski športni gimnastiki organizirana v dveh osnovnih programih: stopenjskem programu in mednarodnem programu.\n\nSTOPENJSKI PROGRAM\n\nStopenjski program je namenjen predvsem dekletom, ki se z gimnastiko ukvarjajo rekreativno ali manj intenzivno. Vanj so vključene tudi mlajše začetnice, ki šele začenjajo svojo gimnastično pot. Tekmovanja potekajo po prilagojenem nacionalnem pravilniku, ki ga pripravlja Gimnastična zveza Slovenije. Ta pravilnik poenostavlja zahteve glede sestav, težavnosti in izvedbe ter omogoča postopno in varno usvajanje osnovnih gimnastičnih prvin. Stopenjski program vključuje več stopenj (1 do 5 ter nadalje tudi višje stopnje), pri čemer se zahtevnost postopoma povečuje. Sistem je zasnovan tako, da tekmovalkam omogoča razvoj osnov, občutek za tekmovanje ter postopno napredovanje.\n\nMEDNARODNI PROGRAM\n\nMednarodni program je namenjen tekmovalkam, ki trenirajo gimnastiko bolj resno (pogosto že od mlajših kategorij dalje). V tem programu tekmovalke nastopajo po pravilih Mednarodne gimnastične zveze (FIG), ki določa sestavo vaj, vrednotenje težavnosti (D-ocena) in izvedbe (E-ocena). Ta pravilnik se uporablja na vseh najvišjih tekmovanjih, kot so svetovna prvenstva in olimpijske igre, ter zagotavlja enotne standarde ocenjevanja na mednarodni ravni.\n\nPREHAJANJE MED PROGRAMOMA\n\nV praksi tekmovalke pogosto začnejo v stopenjskem programu, kjer pridobijo osnovno znanje. Tiste, ki nadaljujejo z bolj intenzivnim treningom, kasneje preidejo v mednarodni program. Tekmovalke, ki že od začetka trenirajo na višji ravni, pa lahko v mednarodnem programu nastopajo že v mlajših kategorijah.")},
]

def main():
    print("Building ChromaDB index...")
    persist_dir = os.path.join(os.path.dirname(__file__), "chroma_db")
    splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=100)
    embeddings = OnnxEmbeddings()
    langchain_docs = []
    for doc in DOCUMENTS:
        for chunk in splitter.split_text(doc["content"]):
            langchain_docs.append(Document(
                page_content=chunk,
                metadata={"title": doc["title"], "language": doc["language"], "category": doc["category"]},
            ))
    print(f"Embedding {len(langchain_docs)} chunks...")
    Chroma.from_documents(langchain_docs, embeddings, persist_directory=persist_dir)
    print("Done. ChromaDB index saved to", persist_dir)

if __name__ == "__main__":
    main()
